/// The commands the front end may call. Each one gets an `allow-*`/`deny-*`
/// permission generated into `permissions/autogenerated/`, which is what the
/// app's capability file then references.
const COMMANDS: &[&str] = &[
    "pick_folder",
    "configure",
    "list_files",
    "read_file",
    "write_file",
    "write_bytes",
    "delete_file",
    "open_document",
];

fn main() {
    tauri_plugin::Builder::new(COMMANDS)
        .android_path("android")
        .build();
}
