/// The commands the front end may call. Each one gets an `allow-*`/`deny-*`
/// permission generated into `permissions/autogenerated/`, which is what the
/// app's capability file then references.
const COMMANDS: &[&str] = &["fetch_text", "download_and_install"];

fn main() {
    tauri_plugin::Builder::new(COMMANDS)
        .android_path("android")
        .build();
}
